### ISSUE TITLE
Design Refinement

### ISSUE THREAD

**Issue by simurai** [electron/electron-api-demos#32]
Here some (random) styling improvements. Feel free to add more.
- [x] Add more contrast to the colors #23
- [x] Fix scrolling after navigating #31
- [x] Add link to repo/source #39
- [x] App icon #49
- [x] Use `<button>` for the `.content h2` so keyboard can be used to open?
- [x] Add some padding at the bottom if there is no pro tip.
